import Head from 'next/head'
import Image from 'next/image'
import 'tailwindcss/tailwind.css'
import Button from '@component/components/Button'
import About from '@component/components/About'
import WhatIDo from '@component/components/WhatIDo'
import Skills from '@component/components/Skills'
import Contact from '@component/components/Contact'
import Footer from '@component/components/Footer'
                        
import Navbar from '@component/components/Navbar'
import Hero from '@component/components/Hero'


export default function Home () {
    return (
        <div>
        <Head>
            <title> Johana Africano | Portfolio</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href=" /flavicon.ico"/>
        </Head>
        <header>
        <Navbar />
        </header>
        <main>
        <Hero />
        <About />
        <WhatIDo />
        <Skills />
        <Contact />
        <Footer />
        </main>
        <main>
        </main>
        </div>
    )
}